# .gitleaks.toml
[extend]
# Extend the base configuration

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api_key|apikey|secret|token)[a-z0-9_]*\s*[=:]\s*['"][0-9a-zA-Z]{32,}['"]'''

[[rules]]
id = "password-in-code"
description = "Password in Code"
regex = '''(?i)(password|passwd|pwd)[a-z0-9_]*\s*[=:]\s*['"][^'"]{3,}['"]'''

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''

[[rules]]
id = "github-token"
description = "GitHub Token"
regex = '''github[_\-\.]?token[\s:=]+['"][0-9a-zA-Z]{35,40}['"]'''

[allowlist]
paths = [
    '''.*test.*''',
    '''.*example.*'''
]